### PR TITLE
fix: added null or empty checks for basic auth credentials

### LINKED ISSUE #97: `getBase64EncodedCredentials` function in CoreHelper didn't check for empty values
**Describe the bug**
When username/password in `CoreHelper.getBase64EncodedCredentials` is null or empty, then it should not encode their combination.

**Expected behavior**
Ignore the AuthorizationHeader if either username or password is missing

**To Reproduce**
Steps to reproduce the bug:
1. Call function `CoreHelper.getBase64EncodedCredentials("username", "")`
2. It will wrongly return a value like `"Basic kjasdhfyausfba"` instead of null.

**Library version number**
For example:  0.6.1

**Environmental details**
For example:
OS: Windows
Runtime version: Java 8

### PR DESCRIPTION
**Pull request by asadali214**
## What
This PR fixes a bug when username/password in CoreHelper.getBase64EncodedCredentials is null or empty, and encoded their combination.

## Why
We need to fail the validation if an authentication parameter value is set to an empty string.

Closes #97

## Type of change
Select multiple if applicable.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [ ] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
N/A

## Breaking change
N/A

## Testing
Unit tests are added to test the new functionality

## Checklist
- [x] My code follows the coding conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added new unit tests

### CODE REVIEW

File: src/test/java/apimatic/core/utilities/CoreHelperTest.java [hunk 1]
```diff
@@ -137,6 +137,24 @@ public void testBase64Encoding() {
         assertEquals(actualEncodedString, expectedEncodedString);
     }
 
+    @Test
+    public void testBase64EncodingWithNullValue() {
```
Comment (sufyankhanrao) [inline src/test/java/apimatic/core/utilities/CoreHelperTest.java:141]: Blocker: Add assertions when the password is null and when both credentials are null.

File: src/test/java/apimatic/core/utilities/CoreHelperTest.java [hunk 2]
```diff
@@ -137,6 +137,24 @@ public void testBase64Encoding() {
...
+        String username = null;
+        String password = "password";
+
+        String actualEncodedString = CoreHelper.getBase64EncodedCredentials(username, password);
+        assertEquals(null, actualEncodedString);
+    }
+
+    @Test
+    public void testBase64EncodingWithEmptyValue() {
```
Comment (sufyankhanrao) [inline src/test/java/apimatic/core/utilities/CoreHelperTest.java:150]: Blocker: Add assertions when the password is empty and when both credentials are empty.

**Review by sufyankhanrao — CHANGES_REQUESTED** [review]

File: src/test/java/apimatic/core/utilities/CoreHelperTest.java (hunk 1 above)
Comment (asadali214) [reply src/test/java/apimatic/core/utilities/CoreHelperTest.java]: done

File: src/test/java/apimatic/core/utilities/CoreHelperTest.java (hunk 2 above)
Comment (asadali214) [reply src/test/java/apimatic/core/utilities/CoreHelperTest.java]: done

**Review by sufyankhanrao — APPROVED** [review]
