### PR TITLE
fix(dynamic-error): removed side effects to keep error cases consistent

### LINKED ISSUE #89: Dynamic error messages are affected due to a side effect of `replacePlaceHolder` in ErrorCases
**Describe the bug**
When setting up the error message for error cases, the `replacePlaceHolder` method in ErrorCase.java modifies the original reason. This resulted in invalid error messages for multiple API Calls when called using the same controller instance

**Expected behavior**
All API Calls need to be treated as separate API Calls and they must not modify the original configuration at any point

**To Reproduce**
Steps to reproduce the bug:
1. Create an ApiCall instance using some configurations, including GlobalErrorCases.
2. Create another ApiCall instance using the same configurations.
3. Execute the ApiCall1 and then execute the ApiCall2.
4. You will find that the returned dynamic error message is invalid for the ApiCall2 i.e. contains the placeholders from ApiCall1.

**Library version number**
For example:  0.4.10

**Environmental details**
For example:
OS: Windows
Runtime version: Java 8

### PR DESCRIPTION
**Pull request by asadali214**
## What
This PR adds a new method `getReason` in ErrorCase that replace `replacePlaceHolder` method. The `getReason` method returns a new error reason instead of replacing the placeHolders in the original reason. 

## Why
We needed to make sure that the GlobalConfigurations are not updated on performing any API Calls

Closes #89

## Type of change
Select multiple if applicable.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [x] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
If a new dependency is being added, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Policy-of-adding-new-dependencies-in-the-core-libraries

## Breaking change
If the PR is introducing a breaking change, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Guidelines-for-maintaining-core-libraries

## Testing
List the steps that were taken to test the changes

## Checklist
- [x] My code follows the coding conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added new unit tests

### CODE REVIEW

File: src/main/java/io/apimatic/core/ErrorCase.java [hunk 1]
```diff
@@ -95,13 +92,33 @@ public static <ExceptionType extends CoreApiException> ErrorCase<ExceptionType>
...
 
-    private void replacePlaceHolder(Response response) {
-        replaceStatusCodeFromTemplate(response.getStatusCode());
-        replaceHeadersFromTemplate(response.getHeaders());
-        replaceBodyFromTemplate(response.getBody());
+    private String getReason(Response response) {
+        if (!isErrorTemplate) {
+            return reason;
+        }
+        String newReason = replaceStatusCodeFromTemplate(response.getStatusCode(), this.reason);
```
Comment (sufyankhanrao) [inline src/main/java/io/apimatic/core/ErrorCase.java:99]: Nits, Blocker: `newReason` variable name should be renamed to `resolvedReason`.

Comment (asadali214) [reply src/main/java/io/apimatic/core/ErrorCase.java]: Fixed

**Review by sufyankhanrao — APPROVED** [review]
LGTM
