### PR TITLE
fix(toString): improve output for additional properties using Map.ToString

### LINKED ISSUE #118: Fix additional properties toString implementation
The current `ToString` override implementation for additional properties generates an unintuitive output that requires improvement.

Utilizing the `Map.ToString` method can help produce a clearer and more structured representation of the additional properties.

Current `toString` output
```
, additionalProp=string
```

### PR DESCRIPTION
**Pull request by hamzamahmood**
## What
- Refactor the ToString override to utilize Map.ToString

## Why
The current ToString override implementation for additional properties generates an unintuitive output that requires improvement.

Previous toString
```
, additionalProp=string
```

Updated toString
```
additionalProperties={additionalProp=string}
```

Closes #118

### CODE REVIEW

File: src/main/java/io/apimatic/core/types/AdditionalProperties.java [hunk 1]
```diff
@@ -93,12 +92,7 @@ public void setAdditionalProperty(String key, T value, boolean skipNullValue) {
 
     @Override
     public String toString() {
-        if (properties.isEmpty()) {
-            return "";
-        }
-
-        return properties.entrySet().stream().map(entry -> entry.getKey() + "=" + entry.getValue())
-                .collect(Collectors.joining(", ", ", ", ""));
+        return properties.toString();
```
Comment (asadali214) [inline src/main/java/io/apimatic/core/types/AdditionalProperties.java:95]: Can you please add a unit test to ensure that this new format stays same after the future releases.
That unit test will also show the expected output of this toString() override.

Comment (hamzamahmood) [reply src/main/java/io/apimatic/core/types/AdditionalProperties.java:95]: Here, we are using java map toString implementation. I don't think we require unit tests for map toString implementation.

Comment (hamzamahmood) [reply src/main/java/io/apimatic/core/types/AdditionalProperties.java:95]: Unit test added

**Review by asadali214 — APPROVED** [review]
