### PR TITLE
style(fix-the-lint-issues): fix the lint the issues of the project

### LINKED ISSUE #38: Fix the Lint issues using the java linter
Linting is the automated checking of your source code for programmatic and stylistic errors. This is done by using a lint tool (otherwise known as a linter). A lint tool is a basic static code analyzer. Run the Linter and resolve the issues.

### PR DESCRIPTION
**Pull request by hamzashoukat94**
Used checkstyle guide for checking the linting issues and fixed the issues suggested by check style. Checkstyle can check many aspects of your source code. It can find class design problems and method design problems. It also has the ability to check code layout and formatting issues.

closes #38

### CODE REVIEW

File: src/main/java/io/apimatic/core/ApiCall.java [hunk 1]
```diff
@@ -117,20 +138,18 @@ public Builder<ResponseType, ExceptionType> responseHandler(
...
 
         /**
-         * 
          * @param action endpointConfiguration {@link Consumer}
          * @return {@link ApiCall.Builder}
          */
-        public Builder<ResponseType, ExceptionType> endpointConfiguration(
-                Consumer<EndpointConfiguration.Builder> action) {
+        public Builder<ResponseType, ExceptionType>
+                endpointConfiguration(Consumer<EndpointConfiguration.Builder> action) {
```
Comment (sufyankhanrao) [inline src/main/java/io/apimatic/core/ApiCall.java:145]: Question: Did the linter enforce you to take the method name to the next line?

File: src/main/java/io/apimatic/core/ResponseHandler.java [hunk 2]
```diff
@@ -171,23 +210,49 @@ private void validateResponse(Context httpContext) throws ExceptionType {
             globalErrorCases.get(errorCode).throwException(httpContext);
         }
 
-        if ((statusCode < 200) || (statusCode > 208)) {
+        if ((statusCode < SUCCESS_CODE) || (statusCode > ALREADY_REPORTED)) {
```
Comment (sufyankhanrao) [inline src/main/java/io/apimatic/core/ResponseHandler.java:213]: Since this is a range where we consider the API call was successful so these constants should be renamed to MIN_SUCCESS_CODE and MAX_SUCCESS_CODE,

**Review by sufyankhanrao — COMMENTED** [review]
Please ensure that all method summaries are ending with dot (.) in order to be consistent.

File: src/main/java/io/apimatic/core/ApiCall.java (hunk 1 above)
Comment (hamzashoukat94) [reply src/main/java/io/apimatic/core/ApiCall.java:145]: No, Formatter moved the method name to the next line.

File: src/main/java/io/apimatic/core/ResponseHandler.java (hunk 2 above)
Comment (hamzashoukat94) [reply src/main/java/io/apimatic/core/ResponseHandler.java]: resolved

**Review by sufyankhanrao — APPROVED** [review]
LGTM
